const constants = {
  START_SEARCH: 'START_SEARCH',
  OPEN_FILM: 'OPEN_FILM',
  OPEN_SEARCH: 'OPEN_SEARCH',
  CHANGE_SORTING: 'CHANGE_SORTING',
  RESULTS_TO_STORE: 'RESULTS_TO_STORE',
  RECOMMENDED_TO_STORE: 'RECOMMENDED_TO_STORE'
};

export default constants;